### ISSUE TITLE
Fishing on elevated positions

### ISSUE THREAD

**Issue by Erivanz** [FireFly-WoW/FireFly-IssueTracker#227]
Fishing on elevated positions

Fishing on elevated positions -> can't be used here i.e. ratschet or booty bay

doesnt work
fishing

fishing should be able

**Comment by Shrizz** [comment]
I can confirm this bug. It seems there is a distance check to the body of water but it's mistakenly including vertical offset (admittedly there should be a limit, but only beyond a minimum threshold, to allow fishing off docks and such). Some pools are also spawning in rivers that you can't fish in due to being too shallow, for example, the southern-most part of the river in Hillsbrad Foothills, near the waterfall.

**Comment by Deathtremor** [comment]
According to this it has been fixed already.

https://github.com/FireFly-WoW/FireFly-IssueTracker/issues/121

**Comment by l1z1xmd** [comment]
Can confirm. I can't fish from the dock in Southshore, i have to be standing on the ground at water level

**Comment by JunkyBulgaria** [comment]
confirmed as well, messed up some variables, working on a fix atm

**Comment by JunkyBulgaria** [comment]
applied test fix, not sure if it works as i haven't tested it

**Comment by Demmye** [comment]
You do not have to be on ground level to fish anymore, but fishing completely ignores LoS, like this: http://i.imgur.com/ZClBpyR.jpg
