### ISSUE TITLE
The culling of stratholme(hc)

### ISSUE THREAD

**Issue by Fearevius** [FireFly-WoW/FireFly-IssueTracker#28]
**Description:**

2 first bosses dont move and take xp for zombies

CHANGEME: Describe the issue here

**Current behaviour:**

CHANGEME: Explain to us (if/how) it currently works.

**Expected behaviour:**

CHANGEME: Explain to us how the issue is supposed to work.

**Steps to reproduce the problem:**

1. Step 1
2. Step 2
3. Step 3

**Screenshots:**

http://imgur.com/a/Iop1O
http://imgur.com/a/qgX7u
url...

**Comment by masterfireyy** [comment]
Hello, 

thanks for the report. I tested all. Can you discribe your problem more detailed? 
You should test also all with movement 1.0 and test it with low damage. 
Most problems are happen when you rush with godmode. All boses are working fine for me only bugs i founded are below. 

Instance fully playable with all events. I also remember on retail was really anoying instance. Wait and walk with Arthas..

http://i.imgur.com/bExkDRK.jpg
http://i.imgur.com/hyb5ao8.jpg


Bugs i found: 
- humen illusionan dont displayed 
- artas at one part was movin to a backpoint because i was to fast i think because of movementspeed.

**Comment by JunkyBulgaria** [comment]
All issues has been fixed, if you find something else or any of the described here feel free to comment/re-open this issue.

**Comment by Fearevius** [comment]
I did as you said, the problem with the movement of the bosses has not disappeared.
http://imgur.com/a/2vMqu
http://imgur.com/a/xgWPa

**Comment by JunkyBulgaria** [comment]
they are not supposed to move, they just spawn there and wait for players to encounter them

**Comment by Fearevius** [comment]
Unfortunately I did not find the video from 3.3.5, but there is this - 6:40

**Comment by JunkyBulgaria** [comment]
Alright, now the report is more clear on what is bugged, thanks for your time.

**Comment by JunkyBulgaria** [comment]
Setting this as lower priority as it's just waypoints.

**Comment by JunkyBulgaria** [comment]
waypoints sniffed and added, needs testing
