### ISSUE TITLE
[DK Quest] The Light of Dawn

### ISSUE THREAD

**Issue by Merilol** [FireFly-WoW/FireFly-IssueTracker#338]
**Description:**

I can't complete this, when i'm on the fight Darion Mograin dies and the fight end and restart.

**Current behaviour:**

After a few minutes of starting the battle they should stop fighting, start a dialogue and finish the quest but they don't stop, only fight  until Darion Mograin dies and Game Over.

**Expected behaviour:**

After a few minutes of starting the battle they should stop fighting, start a dialogue and finish the mission.

**Steps to reproduce the problem:**

1. Step 1
2. Step 2
3. Step 3

**Screenshots:**

https://cloud.githubusercontent.com/assets/28299783/26285669/9e0e828c-3e54-11e7-8793-07461822721e.jpg

**Comment by JunkyBulgaria** [comment]
couldn't reproduce on all live/ptr/dev

**Comment by Siderbas** [comment]
[InGame Ticket] Another player experiencing the same.

**Comment by masterfireyy** [comment]
I've watched some DKs. Normally the Event is made for more players to do it, that is why the current waiting time before the event starts is so long (apr. 5 min). The problem is tho, that there is indeed a bug I think, regarding the healer in opponent team. A Nightelf healer named Rayne casting Tranquilty non-stop. If you kill her, she will instantly respawn. Don't know if that is intended or not. Also people die a lot in this fight, when that happens too much, like the issuecreator you will end up with destroyed items and can't repair somewhere, because there is no repair npc available due to phasing.
