### ISSUE TITLE
Emblems of Valor

### ISSUE THREAD

**Issue by philoudu16** [FireFly-WoW/FireFly-IssueTracker#476]
The 25-man versions of the Naxxramas bosses, Archavon, and the Obsdian Sanctum bosses are all dropping Emblems of Heroism at the moments, instead of Emblems of Valor. No clue about Malygos yet but i expect she probably would drop Emblems of Heroism as well.

**Comment by Somerix** [comment]
up

**Comment by Condrios** [comment]
It would be nice to fix this problem, multiple loot-tables aren't 100% correct but this 1 sure is a pain. I see items i can buy but sadly i can not gain the require badges.
+ affecting the people that are the most committed on the server

**Comment by philoudu16** [comment]
On PTR:

Naxxramas 25 bosses now correctly drop Emblems of Valor.
Obsidian Sanctum 25 is weird: the boss dropped one Emblem of Heroism and 3 Emblems of Triumph (with three drakes up), and the Large Satchel of Spoils contained 5 Emblems of Heroism instead of 5 Emblems of Valor.
Eye of Eternity 25 still drops Emblems of Heroism.
Archavon still drops Emblems of Heroism.

**Comment by JunkyBulgaria** [comment]
Will be fixed, thank you!

**Comment by philoudu16** [comment]
KT only dropped one emblem instead of two also.

**Comment by philoudu16** [comment]
Update for Sartharion:
He now drops 2 Emblems of Valor, and the other drakes only drop gold.
I believe every drake should drop a single Emblem of Valor, and Sartharion should give 1 + number of drakes alive emblems, so that every run of OS gives a total of 4 emblems.
And the Large Satchel gave a single Emblem of Heroism.

I tried EoE again but didn't manage to kill Malygos after 5 tries so I gave up.

Archavon now gives two emblems of Valor as he should.

**Comment by DevSequel** [comment]
made a fix for this and submitted to Fall1n

**Comment by Tr4dY** [comment]
Hello, I can confirm those : 

Naxxramas-25 is fine except for : **The cache of the 4 DK's which give Heroism instead of Valor**
                                                KT should give 2 valor instead of one
Naxxramas-10 :  KT should give two heroism instead of one

Sartharion-25 should give 1 Valor instead of two and each drake should also loot one Valor (for a total of 4, wether you kill them or not) ; plus, the satchel gives one Heroism instead of 5 Valor
Sartharion-10 : He gives two Heroism instead of one, the satchel also gives 1 Heroism instead of 5, and the small drakes should also give one Heroism each

Eye of Eternity : Teleporters after the boss is dead are still unusable as Drake, you have to dismount and click before you hit the ground
                          - Scion flying on disks are still very hard to hit for a melee character, I think their hitboxes should be larger
                          - Emblems are fine, for both 10-25 man raids

**Comment by philoudu16** [comment]
On live:

- Large Satchel of Spoil still gives a single emblem of heroism (instead of 5 emblems of Valor).
- The mini bosses in OS did not drop emblems, the boss dropped two emblems (we did it with one drake alive so the boss part seems right).
- Archavon dropped 2 emblems of Valor as intended.

**Comment by Hardcore-FireFly** [comment]
#527

**Comment by JunkyBulgaria** [comment]
this issue is now fixed
