### ISSUE TITLE
Drop Rates

### ISSUE THREAD

**Issue by MummieSenpai** [FireFly-WoW/FireFly-IssueTracker#493]
**Description:**

dont think they are completly fixed yet

**Current behaviour:**

just killing mobs for quests ect in Zangarmarsh 2 blue and 3 green items in 6 minutes time i may be really lucky or not but i have the feel its still a problem.
while killing mobs for quests the drop rates still seem high (currently questing in outlands).
i hope somone can look over the tables again and adjust where is needed.
**Expected behaviour:*

adjust the droprates to 1x

**Steps to reproduce the problem:**

1. kill mobs
2. record the drops
3. find the problem

**Screenshots:**

here my loot log for the past 15 ish minutes 
http://i.imgur.com/xAEUQlC.png
http://i.imgur.com/LyK8HVx.png

**Comment by Tr4dY** [comment]
By the way, I'll also add that some quest items have odd loot rate.
I remember playing Wotlk and back in the time, I hadn't to clear 6 time a worg cave with 10 monsters to get 6 pelts.. just an example. I find that some quest items should loot more often.

**Comment by frytik** [comment]
@JunkyBulgaria

**Comment by Shrizz** [comment]
I can confirm that the drop rate for greens, blue and epics everywhere seems very high. The other day I got at least 6 epic items, countless blues and there was more green than a city full of orcs! It feels like the rates at like 5x. Regarding quest items, I never really noticed anything here. The only one that stands out so far as being a super low drop rate is Galean's Amulet, but it was like that when it was introduced in TBC, so I believe it's correct.

**Comment by Hardcore-FireFly** [comment]
I personally experienced this. On lower levels, drop rates are even more boosted.
But sometimes on fresh servers, they customize and boost drop rates so that those pioneers in the server will have less trouble doing quests or getting leveling gears (implementing AHBot to stimulate economy is another example on fresh servers).
It's a whole different story when a server gets more population. In that case, drops are usually set back to their original rate.
This may also be the case here. I believe we need confirmation for that.

**Comment by JunkyBulgaria** [comment]
fixed
