### ISSUE TITLE
feralas midsummer festival fire

### ISSUE THREAD

**Issue by haidenton** [FireFly-WoW/FireFly-IssueTracker#515]
**Description:**

CHANGEME: Describe the issue here

**Current behaviour:**

CHANGEME: Explain to us (if/how) it currently works.

**Expected behaviour:**

CHANGEME: Explain to us how the issue is supposed to work.

**Steps to reproduce the problem:**

1. Step 1
2. Step 2
3. Step 3

**Screenshots:**

url...
url...
url...

**Comment by frytik** [comment]
No info, will close in 3 days, if no info come's here

**Comment by Shrizz** [comment]
**ISSUE:**
The Feralas bonfire and the NPCs around it are not present. Thus, you cannot extinguish the bonfire and get achievement credit, blossoms, xp and gold.

Screenshot: https://pasteboard.co/dgQr5POD.jpg

**FIX:**
Put the bonfire and the NPCs there. Just like all the other bonfires in the world (thus far, they all seem to be working, so that's good).

**Comment by philoudu16** [comment]
You're searching in the wrong place. 

For the horde bonfire : coords 72,47 just west of Camp Mojache
For the alliance bonfire: coords 28,43, north west of Feathermoon Stronghold on the island north of Dread Island

**Comment by Shrizz** [comment]
Hmm, ok I will investigate and report back. The information I found elsewhere suggested it was at the location I was at and I had already circled the stronghold. Thanks for the information :)

**Comment by philoudu16** [comment]
All the locations from http://theworldofwarcrafters.blogspot.fr/2011/06/bonfire-locations-335.html#axzz4kdTZZc00 were correct if ever you have some similar issue :)
